// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/battle": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "battles"
                ],
                "summary": "Get battle",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/galaxy.Battle"
                        }
                    }
                }
            }
        },
        "/divisions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "divisions"
                ],
                "summary": "List all divisions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/galaxy.Division"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "divisions"
                ],
                "summary": "Create a division",
                "parameters": [
                    {
                        "description": "Division data",
                        "name": "division",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/galaxy.Division"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/galaxy.Division"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/divisions/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "divisions"
                ],
                "summary": "Get a division by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Division ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/galaxy.Division"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "divisions"
                ],
                "summary": "Update a division",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Division ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Division data",
                        "name": "division",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/galaxy.Division"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/galaxy.Division"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "divisions"
                ],
                "summary": "Delete a division",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Division ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fleet-builds": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet-builds"
                ],
                "summary": "List all fleet builds",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/galaxy.FleetBuild"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet-builds"
                ],
                "summary": "Create a fleet build",
                "parameters": [
                    {
                        "description": "FleetBuild data",
                        "name": "fleetBuild",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/galaxy.FleetBuild"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/galaxy.FleetBuild"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fleet-builds/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet-builds"
                ],
                "summary": "Get a fleet build by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "FleetBuild ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/galaxy.FleetBuild"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet-builds"
                ],
                "summary": "Update a fleet build",
                "parameters": [
                    {
                        "type": "string",
                        "description": "FleetBuild ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "FleetBuild data",
                        "name": "fleetBuild",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/galaxy.FleetBuild"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/galaxy.FleetBuild"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet-builds"
                ],
                "summary": "Delete a fleet build",
                "parameters": [
                    {
                        "type": "string",
                        "description": "FleetBuild ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fleet-builds/{id}/ship-models": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet-builds"
                ],
                "summary": "List ship models assigned to a fleet build",
                "parameters": [
                    {
                        "type": "string",
                        "description": "FleetBuild ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/galaxy.FleetBuildToShipModel"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet-builds"
                ],
                "summary": "Assign a ship model to a fleet build",
                "parameters": [
                    {
                        "type": "string",
                        "description": "FleetBuild ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Assignment data",
                        "name": "assignment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/galaxy.FleetBuildToShipModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/galaxy.FleetBuildToShipModel"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/galaxy.FleetBuildToShipModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fleet-builds/{id}/ship-models/{shipModelId}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fleet-builds"
                ],
                "summary": "Unassign a ship model from a fleet build",
                "parameters": [
                    {
                        "type": "string",
                        "description": "FleetBuild ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ShipModel ID",
                        "name": "shipModelId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ship-models": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ship-models"
                ],
                "summary": "List all ship models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/galaxy.ShipModel"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ship-models"
                ],
                "summary": "Create a ship model",
                "parameters": [
                    {
                        "description": "ShipModel data",
                        "name": "shipModel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/galaxy.ShipModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/galaxy.ShipModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ship-models/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ship-models"
                ],
                "summary": "Get a ship model by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ShipModel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/galaxy.ShipModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ship-models"
                ],
                "summary": "Update a ship model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ShipModel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ShipModel data",
                        "name": "shipModel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/galaxy.ShipModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/galaxy.ShipModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ship-models"
                ],
                "summary": "Delete a ship model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ShipModel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "galaxy.Battle": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "post_side_a": {
                    "$ref": "#/definitions/galaxy.Fleet"
                },
                "post_side_b": {
                    "$ref": "#/definitions/galaxy.Fleet"
                },
                "shots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/galaxy.Shot"
                    }
                },
                "side_a": {
                    "$ref": "#/definitions/galaxy.Fleet"
                },
                "side_b": {
                    "$ref": "#/definitions/galaxy.Fleet"
                }
            }
        },
        "galaxy.Division": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "resources_amount": {
                    "type": "integer"
                },
                "tech_attack": {
                    "type": "integer"
                },
                "tech_cargo": {
                    "type": "integer"
                },
                "tech_defense": {
                    "type": "integer"
                },
                "tech_engines": {
                    "type": "integer"
                }
            }
        },
        "galaxy.Fleet": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "owner": {
                    "description": "owner race id",
                    "type": "string"
                },
                "ships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/galaxy.Ship"
                    }
                }
            }
        },
        "galaxy.FleetBuild": {
            "type": "object",
            "properties": {
                "assignedShipModels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/galaxy.ShipModelAssignment"
                    }
                },
                "attack_resources": {
                    "type": "number"
                },
                "cargo_resources": {
                    "type": "number"
                },
                "defense_resources": {
                    "type": "number"
                },
                "division_id": {
                    "type": "string"
                },
                "engine_resources": {
                    "type": "number"
                },
                "id": {
                    "description": "stored to DB",
                    "type": "string"
                },
                "race_id": {
                    "type": "string"
                },
                "usedResources": {
                    "type": "number",
                    "format": "float64"
                }
            }
        },
        "galaxy.FleetBuildToShipModel": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "fleet_build_id": {
                    "type": "string"
                },
                "result_mass": {
                    "type": "number"
                },
                "shipModel": {
                    "description": "not stored to DB directly",
                    "allOf": [
                        {
                            "$ref": "#/definitions/galaxy.ShipModel"
                        }
                    ]
                },
                "ship_model_id": {
                    "type": "string"
                }
            }
        },
        "galaxy.Ship": {
            "type": "object",
            "properties": {
                "destroyed": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "description": "race owner id",
                    "type": "string"
                },
                "tech": {
                    "$ref": "#/definitions/galaxy.ShipTech"
                },
                "version_id": {
                    "type": "string"
                }
            }
        },
        "galaxy.ShipModel": {
            "type": "object",
            "properties": {
                "cargo_mass": {
                    "type": "number"
                },
                "defense_mass": {
                    "type": "number"
                },
                "engine_mass": {
                    "type": "number"
                },
                "guns": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "one_gun_mass": {
                    "type": "number"
                },
                "owner_id": {
                    "type": "string"
                }
            }
        },
        "galaxy.ShipModelAssignment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "shipModel": {
                    "$ref": "#/definitions/galaxy.ShipModel"
                }
            }
        },
        "galaxy.ShipTech": {
            "type": "object",
            "properties": {
                "attack": {
                    "type": "number"
                },
                "cargo_capacity": {
                    "type": "number"
                },
                "defense": {
                    "type": "number"
                },
                "guns": {
                    "type": "integer"
                },
                "mass": {
                    "type": "number"
                },
                "speed": {
                    "type": "number"
                }
            }
        },
        "galaxy.Shot": {
            "type": "object",
            "properties": {
                "destination": {
                    "type": "string"
                },
                "result": {
                    "type": "boolean"
                },
                "source": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Galaktika API",
	Description:      "API for Galaktika galaxy game",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
